version: '3'

services:
  db:
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/datadump.sql
